# Generated by Django 4.2.19 on 2025-03-05 06:10

import audionomy_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('style_prompt', models.CharField(blank=True, max_length=255)),
                ('exclude_style_prompt', models.CharField(blank=True, max_length=255)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('youtube_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file_1', models.FileField(blank=True, upload_to=audionomy_app.models.audio_upload_path)),
                ('audio_file_2', models.FileField(blank=True, upload_to=audionomy_app.models.audio_upload_path)),
                ('audio1_duration', models.FloatField(blank=True, null=True)),
                ('audio2_duration', models.FloatField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='audionomy_app.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
